server:
  port: 9001
spring:
  application:
    name: config_server
  cloud:
    config:
      enabled: false
      server:
        git:
          uri: https://github.com/oskul2021/gloswitch-config-repo.git
          username: albertlionelmalang@gmail.com
          password: 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
