name: GloSwitch CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: maven
    - name: Build Config-server with Maven
      run: cd config_server/;mvn clean install --file pom.xml -DskipTests;cd ..
    - name: Build discovery_service with Maven
      run: cd discovery_service/;mvn clean install --file pom.xml -DskipTests;cd ..
      
    - name: Run Config-server
      run: sudo kill -9 `sudo lsof -t -i:9001` & sudo java -jar /home/ubuntu/config-server/_work/gloswitch237/gloswitch237/config_server/target/config_server.jar
    - name: Run discovery_service
      run: sudo kill -9 `sudo lsof -t -i:8761` & sudo java -jar /home/ubuntu/config-server/_work/gloswitch237/gloswitch237/discovery_service/target/discovery_service.jar
